---
# yamllint disable rule:indentation
site_name: Learn GCP
nav:
  - Home: index.md
  - Help: help.md
  - About: about.md
theme:
  name: material
  favicon: "assets/images/favicon.ico"
repo_name: "jamesWoolfenden/learn-gcp-web"
repo_url: "https://github.com/jamesWoolfenden/learn-gcp-web"
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# plugins
plugins:
  - search
  - minify:
      minify_html: true
  - mkdocs-add-teaser:
      teaser_class: "teaser"
# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - type: "github"
      link: "https://github.com/jameswoolfenden"
    - type: "twitter"
      link: "https://twitter.com/JimWoolfenden"
    - type: "linkedin"
      link: "https://www.linkedin.com/in/jameswoolfenden/"

# Copyright
copyright: "Copyright &copy; 2019 - 2020 James Woolfenden"
site_author: "James Woolfenden"
